language: node_js
node_js: 8

env:
  - GIT_AUTHOR_NAME=電ちゃん
  - GIT_AUTHOR_EMAIL=inzuma.love.225@gmail.com
  - GIT_COMMITTER_NAME=電ちゃん
  - GIT_COMMITTER_EMAIL=inzuma.love.225@gmail.com

script:
  - npm run lint
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - npm run release
